import { useEffect, useState } from 'react';
import { Calculator, ExternalLink } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { api } from '../services/api';
import { useProjeto } from '../hooks/useProjeto';
import { CabecalhoPagina, EstadoVazio, Mensagem } from '../components/ui/Estados';

export function AvaliacoesPage() {
  const { projetoId } = useProjeto();
  const navegar = useNavigate();
  const [entidades, setEntidades] = useState([]);
  const [bases, setBases] = useState([]);
  const [formulario, setFormulario] = useState({ entidade_id: '', base_referencia_id: '', periodo: '' });
  const [resultado, setResultado] = useState(null);
  const [consultaId, setConsultaId] = useState('');
  const [mensagem, setMensagem] = useState(null);
  useEffect(() => { if (!projetoId) return; Promise.all([api.get(`/entidades?projeto_id=${projetoId}`), api.get('/bases')]).then(([e, b]) => { setEntidades(e.filter((item) => item.ativa)); setBases(b); }).catch((e) => setMensagem({ tipo: 'erro', texto: e.message })); }, [projetoId]);
  async function calcular(evento) { evento.preventDefault(); try { const dados = await api.post('/avaliacoes', { entidade_id: Number(formulario.entidade_id), base_referencia_id: Number(formulario.base_referencia_id), periodo: formulario.periodo }); setResultado(dados); localStorage.setItem('globalscore:ultima-avaliacao-id', dados.id); setMensagem({ tipo: 'sucesso', texto: 'Avaliação calculada e vinculada à Base de Referência.' }); } catch (erro) { setMensagem({ tipo: 'erro', texto: erro.message }); } }
  async function consultar(evento) { evento.preventDefault(); try { const dados = await api.get(`/avaliacoes/${consultaId}`); setResultado(dados); localStorage.setItem('globalscore:ultima-avaliacao-id', dados.id); } catch (erro) { setMensagem({ tipo: 'erro', texto: erro.message }); } }
  return <div><CabecalhoPagina sobretitulo="Resultados calculados" titulo="Avaliações" descricao="Escolha a entidade, a Base congelada e o período. Percentis e Global Score são calculados pela API." />{mensagem && <Mensagem tipo={mensagem.tipo}>{mensagem.texto}</Mensagem>}{!projetoId ? <EstadoVazio titulo="Nenhum projeto selecionado" descricao="Selecione um projeto antes de calcular uma avaliação." /> : <div className="dashboard-grid dashboard-grid--formularios"><section className="painel"><span className="sobretitulo">Nova avaliação</span><h2>Calcular resultado mensal</h2><form className="formulario" onSubmit={calcular}><label>Entidade<select required value={formulario.entidade_id} onChange={(e) => setFormulario({ ...formulario, entidade_id: e.target.value })}><option value="">Selecione</option>{entidades.map((item) => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></label><label>Base de Referência<select required value={formulario.base_referencia_id} onChange={(e) => setFormulario({ ...formulario, base_referencia_id: e.target.value })}><option value="">Selecione</option>{bases.map((item) => <option key={item.id} value={item.id}>{item.nome} · v{item.versao} · {item.status}</option>)}</select></label><label>Período<input type="month" required value={formulario.periodo} onChange={(e) => setFormulario({ ...formulario, periodo: e.target.value })} /></label><button className="botao botao--primario"><Calculator />Calcular avaliação</button></form></section><section className="painel"><span className="sobretitulo">Consulta reproduzível</span><h2>Buscar avaliação por ID</h2><form className="formulario formulario--linha" onSubmit={consultar}><label>ID da avaliação<input type="number" min="1" required value={consultaId} onChange={(e) => setConsultaId(e.target.value)} /></label><button className="botao botao--secundario">Consultar</button></form><p className="nota-interface">A API atual consulta avaliações individualmente. Ainda não existe listagem histórica.</p></section></div>}{resultado && <section className="painel resultado-avaliacao"><div><span className="sobretitulo">Resultado real da API</span><h2>Global Score <strong>{resultado.global_score != null ? resultado.global_score.toFixed(1).replace('.', ',') : 'incompleto'}</strong></h2><p>{resultado.periodo} · {resultado.status} · Base #{resultado.base_referencia_id}</p></div><button className="botao botao--primario" onClick={() => navegar('/dashboard')}>Abrir visão analítica<ExternalLink /></button></section>}</div>;
}
